version: '3.4'                                                                                                             
                                                                                                                           
services:                                                                                                                  
  api:                                                                                                                 
    image: registry.gitlab.com/myhealthnetwork/myhealthnetwork                                                                                                 
    networks:                                                                                                              
      - server-net                                                           
    labels:                                                                                                              
      - "traefik.enable=true"                                                                                            
      - "traefik.port=8001"                                                                                            
      - "traefik.docker.network=server-net"                                                                             
      - "traefik.backend=api"
      - "traefik.frontend.rule=Host:api.my-health-network.be"                                                                                        
                                                                                                                           
networks:                                                                                                                  
  server-net:                                                                                                             
    external: true                                                                                                         